theme: jekyll-theme-minima
title: Transcription typémique sur l’écriture de L. Meigret (1500-1558)
description: Pour une philologie progressive des textes grammaticaux et orthographistes de Louis Meigret (1500 ca -1558 ca)
